### ISSUE TITLE
bi_lstm执行报错

### ISSUE THREAD

**Issue by wjqy1510** [yongyehuang/Tensorflow-Tutorial#1]
y_pred = bi_lstm(X_inputs) 运行这一步时，将X_inputs当成普通参数运行了，导致出错，这该如何解决？

ValueError                                Traceback (most recent call last)
<ipython-input-31-dcc709796411> in <module>()
    121 
    122 
--> 123 y_pred = bi_lstm(X_inputs)
    124 # adding extra statistics to monitor
    125 # y_inputs.shape = [batch_size, timestep_size]

<ipython-input-31-dcc709796411> in bi_lstm(X_inputs)
     49     """build the bi-LSTMs network. Return the y_pred"""
     50     # ** 0.char embedding
---> 51     embedding = tf.get_variable("embedding", [vocab_size, embedding_size], dtype=tf.float32)
     52     # X_inputs.shape = [batchsize, timestep_size]  ->  inputs.shape = [batchsize, timestep_size, embedding_size]
     53     inputs = tf.nn.embedding_lookup(embedding, X_inputs)

d:\set up\python352\lib\site-packages\tensorflow\python\ops\variable_scope.py in get_variable(name, shape, dtype, initializer, regularizer, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter)
   1063       collections=collections, caching_device=caching_device,
   1064       partitioner=partitioner, validate_shape=validate_shape,
-> 1065       use_resource=use_resource, custom_getter=custom_getter)
   1066 get_variable_or_local_docstring = (
   1067     """%s

d:\set up\python352\lib\site-packages\tensorflow\python\ops\variable_scope.py in get_variable(self, var_store, name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter)
    960           collections=collections, caching_device=caching_device,
    961           partitioner=partitioner, validate_shape=validate_shape,
--> 962           use_resource=use_resource, custom_getter=custom_getter)
    963 
    964   def _get_partitioned_variable(self,

d:\set up\python352\lib\site-packages\tensorflow\python\ops\variable_scope.py in get_variable(self, name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter)
    365           reuse=reuse, trainable=trainable, collections=collections,
    366           caching_device=caching_device, partitioner=partitioner,
--> 367           validate_shape=validate_shape, use_resource=use_resource)
    368 
    369   def _get_partitioned_variable(

d:\set up\python352\lib\site-packages\tensorflow\python\ops\variable_scope.py in _true_getter(name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource)
    350           trainable=trainable, collections=collections,
    351           caching_device=caching_device, validate_shape=validate_shape,
--> 352           use_resource=use_resource)
    353 
    354     if custom_getter is not None:

d:\set up\python352\lib\site-packages\tensorflow\python\ops\variable_scope.py in _get_single_variable(self, name, shape, dtype, initializer, regularizer, partition_info, reuse, trainable, collections, caching_device, validate_shape, use_resource)
    662                          " Did you mean to set reuse=True in VarScope? "
    663                          "Originally defined at:\n\n%s" % (
--> 664                              name, "".join(traceback.format_list(tb))))
    665       found_var = self._vars[name]
    666       if not shape.is_compatible_with(found_var.get_shape()):

ValueError: Variable embedding already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "d:\set up\python352\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
    self._traceback = _extract_stack()
  File "d:\set up\python352\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "d:\set up\python352\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)

**Comment by yangxunpeng** [comment]
我也是遇到y_pred = bi_lstm(X_inputs) 这个问题了

**Comment by yongyehuang** [comment]
你好！上面报错：ValueError: Variable embedding already exists, disallowed. 意思是说 embedding这个变量已经定义过了，不能重复定义。造成这个错误的原因可能是你已经执行过**模型构造**的那段代码了，可能某个地方不对你做了修改，然后重新执行第二次，这时候就会报这个错。
notebook  和 .py 文件不同，你需要 restart 这个notebook 重新执行。这样可能比较麻烦，不过你可以先执行**模型构造**这段代码，没有问题了你再执行其他部分数据处理的代码即可。

之前写的代码比较乱，我又改了一下，现在用的版本是 tf 1.2.1
