### ISSUE TITLE
mnist = input_data.read_data_sets('MNIST_data', one_hot=True) 导入数据集mnist报错

### ISSUE THREAD

**Issue by fdrong** [yongyehuang/Tensorflow-Tutorial#13]
http://blog.csdn.net/jerr__y/article/details/57084077
导入数据集的时候报错了： urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>
原因是：from tensorflow.examples.tutorials.mnist import input_data
               mnist = input_data.read_data_sets('MNIST_data', one_hot=True) 源代码里面默认的source_url是：DEFAULT_SOURCE_URL = 'https://storage.googleapis.com/cvdf-datasets/mnist/' 谷歌无法访问：
换成：mnist = input_data.read_data_sets('MNIST_data', one_hot=True, source_url='http://yann.lecun.com/exdb/mnist/')

**Comment by yongyehuang** [comment]
@fdrong 谢谢指出问题
