### ISSUE TITLE
为什么LSTM分词模型换了个数据集就不行了？

### ISSUE THREAD

**Issue by Traeyee** [yongyehuang/Tensorflow-Tutorial#3]
我有一个10000条的数据集，换成这个之后acc一定在0.29左右变化，cost为nan，这是为何？

**Comment by yongyehuang** [comment]
@Traeyee 你好，感谢你的提问。你换了数据集之后 acc 在 0.29 这个好像跟随机差不多了。cost 为 nan 应该是模型根本就没有优化起来。1. 可能在反向传播的时候可能有问题，你可以尝试把学习率调小一些试试。2.检查一下单词的类别处理成 id 有没有问题。3.会不会是版本不同某些地方写法不同出了 bug，但是没有报错。

**Comment by Traeyee** [comment]
@yongyehuang 我又换了一个数据集，用jieba结合我自己词典标的，acc在0.88左右，但cost依然为nan。1. 从之前到最后一次实验，我都试过把学习率调为0，只要是那些大机构的数据集如PKU、MSR之类的不管学习率怎么样都不会爆炸，但只要里面有我自己标的数据（格式是没问题的）就会爆炸，我标的是用医学类词典标的。2. 这个问题我查过，但我代码基本没有变动，用的还是4tags应该没有问题，但tensorflow在运行的时候怎么查 y_inputs 的值啊，能不能简单地告诉我一下。3. 用的是1.2.1版本

**Comment by yongyehuang** [comment]
@Traeyee 在TensorFlow 运行的时候，如果你想看某个 tensor 的值，直接使用 sess.run(tensor) 就能得到它的值了。你可以在 notebook 中逐步把可能出错的地方 print 出来，看看是不是有什么地方处理不对。

**Comment by z744364418p** [comment]
我也遇到同样的问题，换个数据cost=nan,能不能将您的数据预处理代码分享下

**Comment by yongyehuang** [comment]
@z744364418p 你好，所有的数据预处理的代码都在 .ipynb 文件中写出来了。如果可以的话，能不能把你的数据和处理数据的方式发给我一下，我跑下代码看看是什么问题。我的邮箱是： yongye@bupt.edu.cn，如果数据太大的话可以传到云盘分享给我，谷歌，百度云盘都行。

**Comment by yongyehuang** [comment]
@z744364418p 我已经处理完你提供的数据而且模型应该没有出现 nan 的问题，所以我怀疑是你处理数据出了问题。 处理数据和模型的代码都发给你邮箱了。
