### ISSUE TITLE
OutOfRange Error

### ISSUE THREAD

**Issue by ShiningRuby** [yongyehuang/Tensorflow-Tutorial#4]
OutOfRangeError (see above for traceback): RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 100, current size 0)
	 [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]

when i run the tfrecord-3-image-reader.py,the error occurred.How to solve it?

**Comment by yongyehuang** [comment]
@ShiningRuby I rerun tfrecord-3-image-writer.py and tfrecord-3-image-reader.py and find no errors. 
Please make sure that you ran 'tfrecord-3-image-writer.py' first and successfully created the tfrecord files  '../data/training.tfrecord'.

**Comment by ShiningRuby** [comment]
I run tfrecord-3-image-writer.py and tfrecord-3-image-reader.py,and no error happens.I use the outcome of covert_to_tfrecord of tensorflow-101 last time,so the error occurred.Thanks for your reply！ @yongyehuang
