### ISSUE TITLE
Multi—LSTM在Android端准确率下降很多

### ISSUE THREAD

**Issue by KaneHui** [yongyehuang/Tensorflow-Tutorial#5]
我正在做一个文本分类的项目，用到的是Multi-LSTM，在PC端的准确率大概在88%，而在android端的准确率则只有30%，用CNN的话，PC端和Android端的准确率都有99%，相差不大，想知道您是否遇到过类似的情况？

**Comment by yongyehuang** [comment]
@KaneHui 我没有在 Android 端跑过网络，不太了解。我觉得你可以逐步测试看看是哪里出了问题：先单层 LSTM 看看有没有问题；如果单层 LSTM 效果一致的话，你得找找 Android 端的代码实现是不是有问题了。如果单层也有问题，换个简单的数据集试试，比如找 MNIST 试试，看看数据有没有问题。

**Comment by KaneHui** [comment]
`init_state = mlstm_cell.zero_state(batch_size, dtype=tf.float32)`
多谢，我在想，可不可能是因为这个原因，我们在训练以及测试的时候，初始状态的向量的长度为batch_size，通常这个值是一个较大的值，而我们在Android端进行inference的时候，batch_size=1，
也就是我们初始化状态的维度不统一，导致inference的结果和训练结果不一致？

**Comment by z744364418p** [comment]
您的pandas当时是什么版本？

**Comment by KaneHui** [comment]
0.20.1,但我好像没有调用个pandas
