### ISSUE TITLE
 Bi-directional LSTM 这个demo中，没有看明白字向量怎么弄的

### ISSUE THREAD

**Issue by qujinqiang** [yongyehuang/Tensorflow-Tutorial#8]
如题，看代码好像没有使用到字向量
self.embedding = tf.get_variable("embedding", [vocab_size, self.embedding_size], dtype=tf.float32)
这一步只是是不是可以理解为创建了一个空的字向量？
还有如果字不在集合中的话，查找字直接报错，请问这块如何优化

**Comment by yongyehuang** [comment]
@qujinqiang 你好，字向量本来就是一个矩阵。
1. 一般有两种方式来初始化字向量矩阵：一是你可以使用现成的 word2vec 工具预训练得到一个字向量矩阵，用这个预训练好的矩阵进行初始化；二是直接随机初始化，我的代码中就是随机初始化。

2.如果一个字不在集合中肯定会报错的，如果你的数据中有些字不在集合中（比如去停用词以后，停用词就不在集合中），你可以设置一个特殊符号（ 如'<UNK>' ）来表示所有不在集合中字，然后在你的字向量矩阵中需要增加一行对应给这个符号就可以了。

**Comment by qujinqiang** [comment]
@yongyehuang 非常感谢您百忙之中的回复
1、第一为问题我弄明白了，现在想问下随机初始化跟使用字向量，不知道你有没有对比过两者的识别率差别；我目前在基于你这份代码改动，后续试试两者的差别；
2、第二个问题我也弄明白了，我会做下相关改动
后续有问题，还望不吝赐教；
能方便加个QQ吗，好让我近距离膜拜大神；鄙人QQ：273459197

**Comment by yongyehuang** [comment]
@qujinqiang 是否需要进行预训练需要结合你的数据集来考虑。**一般来说，使用预训练的词向量会更好一些。**

如果你的数据集本身就很大的话（比如上千万个句子），可以随机初始化，网络自己就可以学到比较好的字向量矩阵。

如果你的数据集比较小（比如只有几万个句子），那么你可以找一个（最好相关的）很大的数据集来预训练，得到字向量矩阵，这样会比你自己在小数据集上随机初始化学习到的结果要好。

我这里只是说明一下怎么用，没考虑这些，所以直接初始化了，你可以根据自己的需要做改进。

**Comment by qujinqiang** [comment]
@yongyehuang

**Comment by qujinqiang** [comment]
@yongyehuang 谢谢大神的解答
还有点小疑问
self.embedding = tf.get_variable("embedding", [vocab_size, self.embedding_size], dtype=tf.float32)
这块代码是随机初始化的字向量，你提到 “网络可以学习到比较好的字向量”；你的意思是在训练LSTM的同时更新 self.embedding吗？

**Comment by yongyehuang** [comment]
@qujinqiang 对，就是这个意思。
