### ISSUE TITLE
关于LSTM的一点问题

### ISSUE THREAD

**Issue by GehenHe** [yongyehuang/Tensorflow-Tutorial#9]
你好,请教下两个问题:
    1.`hidden_size = 256`是不是就是输出状态向量的长度?
    2.`layer_num = 2`这个是什么意思,这个和[理解lstm](http://www.jeyzhang.com/understanding-lstm-network.html)中的哪个概念是对应的?

谢谢 :)

**Comment by yongyehuang** [comment]
@GehenHe 
1. 对。hidden_size 指的是输出状态向量的长度。
2. layer_num 指的是 LSTM 的层数，参考 http://blog.csdn.net/jerr__y/article/details/61195257 中 RNN 按照时间步展开的图，该图每行就是一层。《理解 LSTM》这篇文章讲的是单层 LSTM 的结构，没有讲到层数。

**Comment by GehenHe** [comment]
你好,
     再叨扰下,问下`(cell_output, state) = mlstm_cell(X[:, timestep, :],state)`,这里的`cell_output`和`state`中的h是一样的吗?我把这两个求差,发现并不为0.所以想问下这个`cell_output`是根据什么计算的

谢谢 :)

**Comment by GehenHe** [comment]
哦哦,搞懂了,`cell_output`是经过drop_out的`hidden_state`,中间就差了些drop_out的数值...

0.O!
